Feature/coininfopage
cristhianbenitez/crypto-app pull request #6
Opened 2021-12-02 01:26 UTC by cristhianbenitez

2021-12-05 20:13 UTC, yoloOnTheBattlefield requested changes
Why are you not using absolute imports bro?

2021-12-05 20:13 UTC, yoloOnTheBattlefield commented on src/Components/AllTimeInfo/AllTimeInfo.js
> +  var atlDate = new Date(props.atlDate).toGMTString();
wtf var

2021-12-05 20:13 UTC, yoloOnTheBattlefield commented on src/Components/CurrencyConverter/CurrencyConverter.js
> +    21;
what is 21 supposed to do?

2021-12-05 20:13 UTC, yoloOnTheBattlefield commented on src/Components/CurrencyConverter/CurrencyConverter.js
> +    };
what are you doing here?

2021-12-05 20:13 UTC, yoloOnTheBattlefield commented on src/Components/IntervalDropdown/IntervalDropdown.js
> +    this.toggle;
and this?

2021-12-05 20:55 UTC, cristhianbenitez commented on src/Components/CurrencyConverter/CurrencyConverter.js
> +    21;
lol, fixed

2021-12-05 21:30 UTC, cristhianbenitez commented
> and this? 

trying to target the text content to update the dropdown title, now i used a another approach

2021-12-05 21:31 UTC, cristhianbenitez commented
> what are you doing here? 

trying to swap

2021-12-07 00:23 UTC, yoloOnTheBattlefield requested changes

2021-12-07 00:23 UTC, yoloOnTheBattlefield commented on src/Components/ChartsLegend/ChartsLegend.js
> +import { formattedNumber, todayDate } from 'Utils';
new line

2021-12-07 00:23 UTC, yoloOnTheBattlefield commented on src/Components/CoinInfo/CoinInfo.styles.js
> +import styled from 'styled-components';
styled before link

2021-12-07 00:23 UTC, yoloOnTheBattlefield commented on src/Components/CoinInfo/CoinInfo.styles.js
> +`;
you have with some variables a new line between them, some without. pick one

2021-12-07 00:23 UTC, yoloOnTheBattlefield commented on src/Components/CoinsListItem/CoinsListItem.js
> +      ('====================================');
do you need this?

2021-12-07 00:23 UTC, yoloOnTheBattlefield commented on src/Components/IntervalDropdown/IntervalDropdown.styles.js
> +export const DropDownList = styled.ul`
same here

2021-12-07 00:23 UTC, yoloOnTheBattlefield commented on src/Components/SubNavbar/SubNavbar.styles.js
>  import styled from 'styled-components';
stled before relative imports

2021-12-07 00:23 UTC, yoloOnTheBattlefield commented on src/Pages/CoinInformation/CoinInformation.styles.js
> +  // General Div
no need for a comment

2021-12-07 00:23 UTC, yoloOnTheBattlefield commented on src/Pages/CoinInformation/CoinInformation.styles.js
> +import styled from 'styled-components';
abs before rel

2021-12-07 00:23 UTC, yoloOnTheBattlefield commented on src/Pages/Coins/Coins.js
>  import React, { Component } from 'react';
absolute before rel

2021-12-07 00:23 UTC, yoloOnTheBattlefield commented on src/index.js
> +import App from 'App';
abs before rel

2021-12-08 18:04 UTC, yoloOnTheBattlefield requested changes

2021-12-08 18:04 UTC, yoloOnTheBattlefield commented on src/Components/CurrencyConverter/CurrencyConverter.js
> +        : this.state.currencies[0]?.currencyValue *
you can extract currency value in a variable

2021-12-08 18:04 UTC, yoloOnTheBattlefield commented on src/Components/Dropdown/Dropdown.styles.js
> +import Currency from 'Assets/CurrencyIcon.svg';
assets lowercase

2021-12-08 18:04 UTC, yoloOnTheBattlefield commented on src/Components/IntervalDropdown/IntervalDropdown.js
> +          }}
use short form
onClick={this.toggle}

2021-12-08 18:04 UTC, yoloOnTheBattlefield commented on src/Components/IntervalDropdown/IntervalDropdown.styles.js
> +import styled from 'styled-components';
absolute before relative

2021-12-08 18:04 UTC, yoloOnTheBattlefield commented on src/Components/LinkContainer/LinkContainer.js
> +      ) : null}
can use logical or `&&`

2021-12-08 18:04 UTC, yoloOnTheBattlefield commented on src/Components/LinkContainer/LinkContainer.styles.js
> +import styled from 'styled-components';
abs before rel

2021-12-08 18:04 UTC, yoloOnTheBattlefield commented on src/Components/Navbar/Navbar.js
> +      ('err');
huh?

2021-12-08 18:04 UTC, yoloOnTheBattlefield commented on src/Helpers/WithRouter.js
>  // With Router Higher Order Component
delete this

2021-12-09 18:08 UTC, yoloOnTheBattlefield requested changes

2021-12-09 18:08 UTC, yoloOnTheBattlefield commented on src/Components/CoinsListItem/CoinsListItem.js
> +      const conditionalRenderArrow = (price) =>
find a better name

2021-12-09 18:08 UTC, yoloOnTheBattlefield commented on src/Components/CoinsListItem/CoinsListItem.js
> +                      index % percentageBarColors.left.length
put this in a variable and reuse it

2021-12-09 18:08 UTC, yoloOnTheBattlefield commented on src/Components/CoinsListItem/CoinsListItem.js
> +                      ]
const color =  percentageBarColors.left[ index % percentageBarColors.left.length ] and then you can reuse it. DRY

2021-12-09 18:08 UTC, yoloOnTheBattlefield commented on src/Components/IntervalDropdown/IntervalDropdown.js
>            }}
could be in one line

2021-12-09 18:08 UTC, yoloOnTheBattlefield commented on src/Components/index.js
>  // export all components from here
no need for obvious comment

2021-12-10 18:05 UTC, yoloOnTheBattlefield approved these changes

2021-12-11 00:42 UTC, merged